### ISSUE TITLE
头像显示有错误

### ISSUE THREAD

**Issue by frankyyzy** [frankyyzy/wxmeet#42]
profile pictures have undefined behaviors. 
May show up wrong profile pictures when one attendee changes their available times.

**Comment by frankyyzy** [comment]
how to reproduce: 
create a event, select time , share to friend, they select some time.
exit miniprogram, edit time and deselect all time. go back to profile page and go to event page again.

**Comment by frankyyzy** [comment]
pictures some times doesn't load, sometimes change order while touching

**Comment by frankyyzy** [comment]
turns out need to hold for a long time.

**Comment by frankyyzy** [comment]
possible solution: preprocessing profile pictures

**Comment by kwkarlwang** [comment]
The problem is fixed with preprocessing and html image hidden.
